Repository mergifyio-testing/functional-testing-repo-jd, pull requests merged in 2021-11, with the labels that each got.

#147 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#148 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#154 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#157 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#162 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#167 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#168 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#176 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#177 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#203 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#214 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#241 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#269 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#275 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#299 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#300 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#306 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#309 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#314 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#319 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#320 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#329 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#330 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#350 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#361 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#372 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#373 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#397 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#425 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#599 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#604 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#611 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#612 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#621 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#661 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#671 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#702 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#703 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#711 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#712 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#744 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#777 test_rebase_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge

#790 test_update_action: pull request n1 from fork
  test1
Labels: merge

#792 test_update_action_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge
